### ISSUE TITLE
The autospoilers don't seems to work and I've read Readme and everything. Can explain how it works maybe ?

### ISSUE THREAD

**Issue by tampermonkey335** [Guy-Adler/GeoFSSpoilersArming#2]
It doesn't seem to work, I've read Readme and everything yunno.

**Comment by Guy-Adler** [comment]
What aircraft have you been using while trying to use the extension?
You also need to press shift+your spoiler toggle key to toggle the spoiler arming

**Comment by ramanshsharma2806** [comment]
what if I am using Shift for the rudder?

**Comment by ramanshsharma2806** [comment]
nvm its working now, I just had to disable the outdated nose wheel steering script
